# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "nil"
    buffer_index_type = 4
    enable_statusline_display_mode = false 
    relativenumber = false
    enable_tabline_filetype_icon = true
    statusline_unicode_symbols = true


# Development Tools
# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'checkers'
open-list = 0

[[layers]]
name = "git"

[[layers]]
name = "VersionControl"


# Misc
# For bookmark feature
[[layers]]
name = 'tools'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
